#
# scrutinizer-ci.com Configuration File
#
# https://scrutinizer-ci.com/docs/
#
build:
    environment:
        php: 7.2.0
filter:
    dependency_paths:
        - vendor/*
    excluded_paths:
        - 'vendor/*'
