#
# scrutinizer-ci.com Configuration File
#
# https://scrutinizer-ci.com/docs/
#
filter:
    excluded_paths:
        - 'vendor/*'
before_commands:
    - 'composer self-update'
    - 'composer install --dev --prefer-dist --no-interaction'
changetracking:
    bug_patterns: ["\bfix(?:es|ed)?\b", "\bclose(?:s|ed)?\b"]
    feature_patterns: ["\badd(?:s|ed)?\b", "\bimplement(?:s|ed)?\b"]
tools:
    # disable copy paste detector and simliarity analyzer
    # because huge number of false-positives and no real value
    php_cpd: false
    php_sim: false
    php_changetracking: true
    php_code_coverage: false
    external_code_coverage:
        timeout: 600
        runs: 3
checks:
    php:
        code_rating: true
        duplication: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
