#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/php for more hints
#
language: php

php: [5.5, 5.6, 7.0]

cache:
  directory:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update
  - composer install --dev --prefer-dist --no-interaction --optimize-autoloader

script:
  - phpunit -c tests/phpunit.xml.dist

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#koch"
    use_notice: true

git:
  depth: 10