#
# .travis.yml - configuration file for the travis continuous integration service
#
# see http://about.travis-ci.org/docs/user/languages/php for more hints
#
language: php

php: [7.1]

sudo: false

cache:
  directory:
    - $HOME/.composer/cache/files

addons:
  apt:
    packages:
      - parallel

before_install:
  - composer self-update
  - composer install --prefer-dist --no-interaction --optimize-autoloader

script:
  # PHP lint
  - >
    echo;
    echo "Running PHP lint";
    find . -name \*.php ! -path "./vendor/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  # PHPUnit
  - phpunit -c tests/phpunit.xml.dist

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml; fi

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#wpnxm"
    use_notice: true
    skip_join: true

git:
  depth: 10